# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_auto_20170313_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp_id', models.CharField(max_length=30, verbose_name='Microsoft ID')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Participant')),
            ],
        ),
    ]
