# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20170130_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('message', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
