# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='position',
            field=models.IntegerField(help_text='The Updates will be shown in ascending order of their position value.'),
        ),
    ]
