# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20170212_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
