# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarohan', '0003_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='roll_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
