# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarohan', '0004_auto_20170313_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='city',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='result',
            name='school',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
