# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarohan', '0005_auto_20170314_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='total_marks',
            field=models.SmallIntegerField(),
        ),
    ]
