# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_auto_20170222_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhavan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('given', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('notes_1000', models.IntegerField(blank=True, default=0, null=True)),
                ('notes_500', models.IntegerField(blank=True, default=0, null=True)),
                ('notes_100', models.IntegerField(blank=True, default=0, null=True)),
                ('notes_50', models.IntegerField(blank=True, default=0, null=True)),
                ('notes_20', models.IntegerField(blank=True, default=0, null=True)),
                ('notes_10', models.IntegerField(blank=True, default=0, null=True)),
                ('draft_number', models.CharField(default=b'', max_length=100)),
                ('draft_amount', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegsoftDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firewallz', models.BooleanField(default=False, verbose_name=b'Passed Firewallz')),
                ('controlz', models.BooleanField(default=False, verbose_name=b'Passed Controlz')),
                ('recnacc', models.BooleanField(default=False, verbose_name=b'Passed RecNAcc')),
                ('group_code', models.CharField(default=b'', max_length=10)),
                ('bill', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Bill')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('vacancy', models.IntegerField()),
                ('a', models.IntegerField(default=0, null=True)),
                ('b', models.IntegerField(default=0, null=True)),
                ('c', models.IntegerField(default=0, null=True)),
                ('d', models.IntegerField(default=0, null=True)),
                ('e', models.IntegerField(default=0, null=True)),
                ('f', models.IntegerField(default=0, null=True)),
                ('bhavan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regsoft.Bhavan')),
            ],
        ),
        migrations.AddField(
            model_name='regsoftdetails',
            name='room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='regsoft.Room'),
        ),
    ]
