# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0002_auto_20170313_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='regsoftdetails',
            name='checkout',
            field=models.BooleanField(default=False, verbose_name=b'Checked Out'),
        ),
    ]
