# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0006_merge_20170322_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='notes_1000',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
