# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regsoft', '0007_bill_notes_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='regsoftdetails',
            name='amount_deducted',
            field=models.IntegerField(default=0),
        ),
    ]
