# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messbill',
            old_name='n1000',
            new_name='n2000',
        ),
        migrations.RenameField(
            model_name='profshowticket',
            old_name='n1000',
            new_name='n2000',
        ),
    ]
