# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messportal', '0002_auto_20170323_0516'),
        ('messportal', '0002_auto_20170322_2252'),
    ]

    operations = [
    ]
