# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={},
        ),
        migrations.AlterField(
            model_name='heading',
            name='weight',
            field=models.IntegerField(help_text=b'Headings will be shown in ascending order of their weights.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(blank=True, help_text=b'DD/MM/YYYY', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.CharField(blank=True, help_text=b'DD/MM/YYYY', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endingtime',
            field=models.CharField(blank=True, help_text=b'HH:MM', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startingtime',
            field=models.CharField(blank=True, help_text=b'HH:MM', max_length=100),
        ),
        migrations.AlterField(
            model_name='tab',
            name='heading',
            field=models.ForeignKey(help_text=b'Headings will be shown in ascending order of their weights.', on_delete=django.db.models.deletion.CASCADE, to='Event.Heading'),
        ),
    ]
