# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20170123_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, help_text=b'DD/MM/YYYY', max_length=100)),
                ('end_date', models.CharField(blank=True, help_text=b'DD/MM/YYYY', max_length=100)),
                ('startingtime', models.CharField(blank=True, help_text=b'HH:MM', max_length=100)),
                ('endingtime', models.CharField(blank=True, help_text=b'HH:MM', max_length=100)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('round_no', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
