# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0002_auto_20170123_1608'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('is_displayed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bitsian', models.BooleanField(default=False)),
                ('uniqueid', models.CharField(blank=True, default=None, max_length=8, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('phone', models.BigIntegerField(null=True)),
                ('alternate_phone', models.BigIntegerField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('social_link', models.CharField(blank=True, max_length=300, null=True)),
                ('pcr_approval', models.BooleanField(default=False)),
                ('fee_paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, verbose_name='IFSC Code')),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('bank_account_no', models.CharField(blank=True, max_length=20, verbose_name='Bank Account No.')),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.College')),
                ('events', models.ManyToManyField(blank=True, to='Event.Event')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Participants',
            },
        ),
    ]
