# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicsubmission',
            name='problem_statement',
            field=models.CharField(max_length=500),
        ),
    ]
