# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tichallenge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college', models.CharField(max_length=200)),
                ('yos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TIChallengeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(default=None, upload_to=tichallenge.models.upload_iot)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='tichallenge.Participant')),
                ('members', models.ManyToManyField(blank=b'True', related_name='members', to='tichallenge.Participant')),
            ],
        ),
    ]
