# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tichallenge', '0002_auto_20170216_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tichallengesubmission',
            options={'verbose_name': 'TI Challenge Submission'},
        ),
    ]
