# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revengg', '0003_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='revengg.Option'),
        ),
    ]
