# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revengg', '0006_auto_20170313_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[(b'Aptitude', b'Aptitude'), (b'Mechanical', b'Mechanical'), (b'Automobile', b'Automobile')], default=b'', max_length=30),
        ),
    ]
