# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0002_auto_20170123_1608'),
        ('registration', '0003_auto_20170313_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('comments', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('position', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('code', models.CharField(default='', max_length=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_team', to='registration.Participant')),
                ('members', models.ManyToManyField(to='registration.Participant')),
            ],
        ),
    ]
