# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20170123_1608'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1name', models.CharField(blank=True, max_length=100)),
                ('var1max', models.PositiveSmallIntegerField(default=10)),
                ('var2name', models.CharField(blank=True, max_length=100)),
                ('var2max', models.PositiveSmallIntegerField(default=10)),
                ('var3name', models.CharField(blank=True, max_length=100)),
                ('var3max', models.PositiveSmallIntegerField(default=10)),
                ('var4name', models.CharField(blank=True, max_length=100)),
                ('var4max', models.PositiveSmallIntegerField(default=10)),
                ('var5name', models.CharField(blank=True, max_length=100)),
                ('var5max', models.PositiveSmallIntegerField(default=10)),
                ('var6name', models.CharField(blank=True, max_length=100)),
                ('var6max', models.PositiveSmallIntegerField(default=10)),
                ('var7name', models.CharField(blank=True, max_length=100)),
                ('var7max', models.PositiveSmallIntegerField(default=10)),
                ('var8name', models.CharField(blank=True, max_length=100)),
                ('var8max', models.PositiveSmallIntegerField(default=10)),
                ('var9name', models.CharField(blank=True, max_length=100)),
                ('var9max', models.PositiveSmallIntegerField(default=10)),
                ('var10name', models.CharField(blank=True, max_length=100)),
                ('var10max', models.PositiveSmallIntegerField(default=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_protected', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.Event')),
                ('judges', models.ManyToManyField(blank=True, to='ems.Judge')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.Label')),
                ('teams', models.ManyToManyField(blank=True, related_name='levels', to='ems.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_frozen', models.BooleanField(default=False)),
                ('var1', models.IntegerField(blank=True, default=None, null=True)),
                ('var2', models.IntegerField(blank=True, default=None, null=True)),
                ('var3', models.IntegerField(blank=True, default=None, null=True)),
                ('var4', models.IntegerField(blank=True, default=None, null=True)),
                ('var5', models.IntegerField(blank=True, default=None, null=True)),
                ('var6', models.IntegerField(blank=True, default=None, null=True)),
                ('var7', models.IntegerField(blank=True, default=None, null=True)),
                ('var8', models.IntegerField(blank=True, default=None, null=True)),
                ('var9', models.IntegerField(blank=True, default=None, null=True)),
                ('var10', models.IntegerField(blank=True, default=None, null=True)),
                ('comments', models.CharField(blank=True, max_length=500)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ems.Judge')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ems.Level')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ems.Team')),
            ],
        ),
    ]
