# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_introreg_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='introreg',
            name='college',
            field=models.CharField(default='', max_length=200),
        ),
    ]
